routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

Auth::routes();
Route::middleware('auth')->group(function () {
    //Role: admin
    Route::name('admin.')->prefix('admin')->group(function () {        
        Route::name('users.')->prefix('/users')->group(function () {
            Route::get('/', 'Admin\UserController@index')->name('index')->middleware('can:list-user');
            Route::get('/create', 'Admin\UserController@create')->name('create')->middleware('can:add-user');
            Route::post('/store', 'Admin\UserController@store')->name('store')->middleware('can:add-user');
            Route::get('/edit/{id}', 'Admin\UserController@edit')->name('edit')->middleware('can:edit-user');
            Route::post('/update/{id}', 'Admin\UserController@update')->name('update')->middleware('can:edit-user');
            Route::get('/destroy/{id}', 'Admin\UserController@destroy')->name('destroy')->middleware('can:delete-user');
        });

        Route::name('roles.')->prefix('/roles')->group(function () {
            Route::get('/', 'Admin\RoleController@index')->name('index')->middleware('can:list-role');
            Route::get('/create', 'Admin\RoleController@create')->name('create')->middleware('can:add-role');
            Route::post('/store', 'Admin\RoleController@store')->name('store')->middleware('can:add-role');
            Route::get('/edit/{id}', 'Admin\RoleController@edit')->name('edit')->middleware('can:edit-role');
            Route::post('/update/{id}', 'Admin\RoleController@update')->name('update')->middleware('can:edit-role');
            Route::get('/destroy/{id}', 'Admin\RoleController@destroy')->name('destroy')->middleware('can:delete-role');
        });

        Route::name('permissions.')->prefix('/permissions')->group(function () {
            Route::get('/', 'Admin\PermissionController@index')->name('index')->middleware('can:list-permission');
            Route::post('/store', 'Admin\PermissionController@store')->name('store')->middleware('can:add-permission');
            Route::get('/destroy/{id}', 'Admin\PermissionController@destroy')->name('destroy')->middleware('can:delete-permission');
        });

        // Role:editor or admin
        Route::name('authors.')->prefix('/authors')->group(function () {
            Route::get('/', 'Admin\AuthorController@index')->name('index')->middleware('can:list-author');
            Route::get('/create', 'Admin\AuthorController@create')->name('create')->middleware('can:add-author');
            Route::post('/store', 'Admin\AuthorController@store')->name('store')->middleware('can:add-author');
            Route::get('/edit/{id}', 'Admin\AuthorController@edit')->name('edit')->middleware('can:edit-author');
            Route::post('/update/{id}', 'Admin\AuthorController@update')->name('update')->middleware('can:edit-author');
            Route::get('/destroy/{id}', 'Admin\AuthorController@destroy')->name('destroy')->middleware('can:delete-author');
        });

        Route::name('products.')->prefix('/products')->group(function () {
            Route::get('/', 'Admin\ProductController@index')->name('index')->middleware('can:list-product');
            Route::get('/create', 'Admin\ProductController@create')->name('create')->middleware('can:add-product');
            Route::post('/store', 'Admin\ProductController@store')->name('store')->middleware('can:add-product');
            Route::get('/edit/{id}', 'Admin\ProductController@edit')->name('edit')->middleware('can:edit-product');
            Route::post('/update/{id}', 'Admin\ProductController@update')->name('update')->middleware('can:edit-product');
            Route::get('/show/{id}', 'Admin\ProductController@show')->name('show')->middleware('can:show-product');
            Route::get('/destroy/{id}', 'Admin\ProductController@destroy')->name('destroy')->middleware('can:delete-product');
        });

        Route::name('owners.')->prefix('/owners')->group(function () {
            Route::get('/', 'Admin\OwnerController@index')->name('index')->middleware('can:list-owner');
            Route::get('/create', 'Admin\OwnerController@create')->name('create')->middleware('can:add-owner');
            Route::post('/store', 'Admin\OwnerController@store')->name('store')->middleware('can:add-owner');
            Route::get('/edit/{id}', 'Admin\OwnerController@edit')->name('edit')->middleware('can:edit-owner');
            Route::post('/update/{id}', 'Admin\OwnerController@update')->name('update')->middleware('can:edit-owner');
            Route::get('/destroy/{id}', 'Admin\OwnerController@destroy')->name('destroy')->middleware('can:delete-owner');
        });

        Route::name('categories.')->prefix('/categories')->group(function () {
            Route::get('/', 'Admin\CategoryController@index')->name('index')->middleware('can:list-category');
            Route::post('/store', 'Admin\CategoryController@store')->name('store')->middleware('can:add-category');
            Route::get('/edit/{id}', 'Admin\CategoryController@edit')->name('edit')->middleware('can:edit-category');
            Route::post('/update/{id}', 'Admin\CategoryController@update')->name('update')->middleware('can:edit-category');
            Route::get('/destroy/{id}', 'Admin\CategoryController@destroy')->name('destroy')->middleware('can:delete-category');
        });

        Route::name('licenses.')->prefix('/licenses')->group(function () {
            Route::get('/', 'Admin\LicenseController@index')->name('index')->middleware('can:list-license');
            Route::get('/create', 'Admin\LicenseController@create')->name('create')->middleware('can:add-license');
            Route::post('/store', 'Admin\LicenseController@store')->name('store')->middleware('can:add-license');
            Route::get('/edit/{id}', 'Admin\LicenseController@edit')->name('edit')->middleware('can:edit-license');
            Route::post('/update/{id}', 'Admin\LicenseController@update')->name('update')->middleware('can:edit-license');
            Route::get('/destroy/{id}', 'Admin\LicenseController@destroy')->name('destroy')->middleware('can:delete-license');
        });
        
        Route::name('contracts.')->prefix('/contracts')->group(function () {
            Route::get('/', 'Admin\ContractController@index')->name('index')->middleware('can:list-contract');
            Route::get('/create', 'Admin\ContractController@create')->name('create')->middleware('can:add-contract');
            Route::post('/store', 'Admin\ContractController@store')->name('store')->middleware('can:add-contract');
            Route::get('/edit/{id}', 'Admin\ContractController@edit')->name('edit')->middleware('can:edit-contract');
            Route::post('/update/{id}', 'Admin\ContractController@update')->name('update')->middleware('can:edit-contract');
            Route::get('/destroy/{id}', 'Admin\ContractController@destroy')->name('destroy')->middleware('can:delete-contract');
            Route::get('/show/{id}', 'Admin\ContractController@show')->name('show')->middleware('can:show-contract');
        });

    });
});

Route::get('/', 'HomeController@index')->name('home.index');

app/Models/Owner.php
<?php

namespace App\Models;

use App\Models\Product;
use Illuminate\Database\Eloquent\Model;

class Owner extends Model
{
    protected $fillable = ["name", "phone", 'email'];

    public function products()
    {
        return $this->hasMany(Product::class);
    }

}

app/Http/Controllers/admin/OwnerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\Admin\Owner\StoreOwnerRequest;
use App\Http\Requests\Admin\Owner\UpdateOwnerRequest;
use App\Services\OwnerService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class OwnerController extends Controller
{
    private $ownerService;

    public function __construct(OwnerService $ownerService)
    {
        $this->ownerService = $ownerService;
    }

    public function index(Request $request)
    {
        $owners = $this->ownerService->getPaginate();
        return view('admin.owners.index', compact('owners'));
    }

    public function create()
    {
        return view('admin.owners.create');
    }

    public function store(StoreOwnerRequest $request)
    {
        $this->ownerService->create($request);
        return Redirect(route('admin.owners.index'))->with('success', 'Thêm chủ sở hữu thành công');
    }

    public function edit($id)
    {
        $owner = $this->ownerService->getById($id);
        return view('admin.owners.edit', compact('owner'));
    }

    public function update(UpdateOwnerRequest $request, $id)
    {
        $this->ownerService->update($request, $id);
        return Redirect(route('admin.owners.index'))->with('success', 'Câp nhật chủ sở hữu thành công');
    }

    public function destroy($id)
    {
        $owner = $this->ownerService->delete($id);
        return response()->json(['owner' => $owner, 'message' => 'Xóa chủ sở hữu thành công']);
    }
}

resources/views/admin/owners/create.blade.php
@extends('layouts.admin')
@section('title', 'Thêm mới chủ sở hữu')
@section('content')
    <div class="content-wrapper">
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6">
                        <form action="{{ route('admin.owners.store') }}" method="POST">
                            @csrf
                            <div class="form-group">
                                <label  class="label-required" for="category_name">Tên chủ sở hữu</label>
                                <input type="text" name="name" class="form-control" value="{{ old('name') }}">
                                @error('name')
                                    <span class="mt-1 text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label  class="label-required" for="category_name">Số điện thoại</label>
                                <input type="text" name="phone" class="form-control" value="{{ old('phone') }}">
                                @error('phone')
                                    <span class="mt-1 text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label  class="label-required" for="category_name">Email</label>
                                <input type="email" name="email" class="form-control" value="{{ old('email') }}">
                                @error('email')
                                    <span class="mt-1 text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            <button type="submit" class="btn btn-primary">Thêm mới</button>
                        </form>
                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
@endsection

resources/views/admin/owners/edit.blade.php
@extends('layouts.admin')
@section('title', 'Sửa thông tin chủ sở hữu')
@section('content')
    <div class="content-wrapper">
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6">
                        <form action="{{ route('admin.owners.update', ["id" => $owner->id]) }}" method="POST">
                            @csrf
                            <div class="form-group">
                                <label  class="label-required" for="category_name">Tên chủ sở hữu</label>
                                <input type="text" value="{{ old('name') ?? $owner->name }}" name="name" class="form-control" >
                                @error('name')
                                    <span class="mt-1 text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label  class="label-required" for="category_name">Số điện thoại</label>
                                <input value="{{ old('phone') ?? $owner->phone }}" type="text" name="phone" class="form-control" >
                                @error('phone')
                                    <span class="mt-1 text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label  class="label-required" for="category_name">Email</label>
                                <input value="{{ old('email') ?? $owner->email }}" type="email" name="email" class="form-control" >
                                @error('email')
                                    <span class="mt-1 text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            <button type="submit" class="btn btn-primary">Cập nhật</button>
                        </form>
                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
@endsection

resources/views/admin/owners/index.blade.php
@extends('layouts.admin')
@section('title', 'Quản lý chủ sở hữu')
@section('content')
    <div class="content-wrapper">
        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="py-3">
                        <a class="btn btn-success btn-sm"
                            href="{{ route('admin.owners.create') }}">Thêm mới</a>
                    </div>
                    <div class="col-md-12 card">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Tên chủ sơ hữu</th>
                                    <th>Email</th>
                                    <th>Phone</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($owners as $owner)
                                    <tr>
                                        <td>{{ $owner->id }}</td>
                                        <td>{{ $owner->name }}</td>
                                        <td>{{ $owner->email }}</td>
                                        <td>{{ $owner->phone }}</td>
                                        <td>
                                            <a href="{{ route('admin.owners.edit', ['id' => $owner->id]) }}"><button
                                                    class="btn btn-info btn-sm">Sửa</button></a>
                                            <button type="button"
                                                data-url="{{ route('admin.owners.destroy', ['id' => $owner->id]) }}"
                                                class="btn btn-danger btn-sm btn-delete">Xóa</button>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        {{ $owners->withQueryString()->links() }}
                    </div>
                    <!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
    </div>
    @endsection
    @section('js')
        <script>
            $('#header-search-form').attr('action', '{{ route('admin.owners.index') }}');
            $('#search-input').attr('placeholder', 'Tìm kiếm chủ sở hữu, email, số điện thoại...');

            $(document).ready(function() {
                $('#search').click(function() {
                    $('#toggle').slideToggle();
                });
            });
        </script>
    @endsection