routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

Auth::routes();
Route::middleware('auth')->group(function () {
    //Role: admin
    Route::name('admin.')->prefix('admin')->group(function () {        
        Route::name('users.')->prefix('/users')->group(function () {
            Route::get('/', 'Admin\UserController@index')->name('index')->middleware('can:list-user');
            Route::get('/create', 'Admin\UserController@create')->name('create')->middleware('can:add-user');
            Route::post('/store', 'Admin\UserController@store')->name('store')->middleware('can:add-user');
            Route::get('/edit/{id}', 'Admin\UserController@edit')->name('edit')->middleware('can:edit-user');
            Route::post('/update/{id}', 'Admin\UserController@update')->name('update')->middleware('can:edit-user');
            Route::get('/destroy/{id}', 'Admin\UserController@destroy')->name('destroy')->middleware('can:delete-user');
        });

        Route::name('roles.')->prefix('/roles')->group(function () {
            Route::get('/', 'Admin\RoleController@index')->name('index')->middleware('can:list-role');
            Route::get('/create', 'Admin\RoleController@create')->name('create')->middleware('can:add-role');
            Route::post('/store', 'Admin\RoleController@store')->name('store')->middleware('can:add-role');
            Route::get('/edit/{id}', 'Admin\RoleController@edit')->name('edit')->middleware('can:edit-role');
            Route::post('/update/{id}', 'Admin\RoleController@update')->name('update')->middleware('can:edit-role');
            Route::get('/destroy/{id}', 'Admin\RoleController@destroy')->name('destroy')->middleware('can:delete-role');
        });

        Route::name('permissions.')->prefix('/permissions')->group(function () {
            Route::get('/', 'Admin\PermissionController@index')->name('index')->middleware('can:list-permission');
            Route::post('/store', 'Admin\PermissionController@store')->name('store')->middleware('can:add-permission');
            Route::get('/destroy/{id}', 'Admin\PermissionController@destroy')->name('destroy')->middleware('can:delete-permission');
        });

        // Role:editor or admin
        Route::name('authors.')->prefix('/authors')->group(function () {
            Route::get('/', 'Admin\AuthorController@index')->name('index')->middleware('can:list-author');
            Route::get('/create', 'Admin\AuthorController@create')->name('create')->middleware('can:add-author');
            Route::post('/store', 'Admin\AuthorController@store')->name('store')->middleware('can:add-author');
            Route::get('/edit/{id}', 'Admin\AuthorController@edit')->name('edit')->middleware('can:edit-author');
            Route::post('/update/{id}', 'Admin\AuthorController@update')->name('update')->middleware('can:edit-author');
            Route::get('/destroy/{id}', 'Admin\AuthorController@destroy')->name('destroy')->middleware('can:delete-author');
        });

        Route::name('products.')->prefix('/products')->group(function () {
            Route::get('/', 'Admin\ProductController@index')->name('index')->middleware('can:list-product');
            Route::get('/create', 'Admin\ProductController@create')->name('create')->middleware('can:add-product');
            Route::post('/store', 'Admin\ProductController@store')->name('store')->middleware('can:add-product');
            Route::get('/edit/{id}', 'Admin\ProductController@edit')->name('edit')->middleware('can:edit-product');
            Route::post('/update/{id}', 'Admin\ProductController@update')->name('update')->middleware('can:edit-product');
            Route::get('/show/{id}', 'Admin\ProductController@show')->name('show')->middleware('can:show-product');
            Route::get('/destroy/{id}', 'Admin\ProductController@destroy')->name('destroy')->middleware('can:delete-product');
        });

        Route::name('owners.')->prefix('/owners')->group(function () {
            Route::get('/', 'Admin\OwnerController@index')->name('index')->middleware('can:list-owner');
            Route::get('/create', 'Admin\OwnerController@create')->name('create')->middleware('can:add-owner');
            Route::post('/store', 'Admin\OwnerController@store')->name('store')->middleware('can:add-owner');
            Route::get('/edit/{id}', 'Admin\OwnerController@edit')->name('edit')->middleware('can:edit-owner');
            Route::post('/update/{id}', 'Admin\OwnerController@update')->name('update')->middleware('can:edit-owner');
            Route::get('/destroy/{id}', 'Admin\OwnerController@destroy')->name('destroy')->middleware('can:delete-owner');
        });

        Route::name('categories.')->prefix('/categories')->group(function () {
            Route::get('/', 'Admin\CategoryController@index')->name('index')->middleware('can:list-category');
            Route::post('/store', 'Admin\CategoryController@store')->name('store')->middleware('can:add-category');
            Route::get('/edit/{id}', 'Admin\CategoryController@edit')->name('edit')->middleware('can:edit-category');
            Route::post('/update/{id}', 'Admin\CategoryController@update')->name('update')->middleware('can:edit-category');
            Route::get('/destroy/{id}', 'Admin\CategoryController@destroy')->name('destroy')->middleware('can:delete-category');
        });

        Route::name('licenses.')->prefix('/licenses')->group(function () {
            Route::get('/', 'Admin\LicenseController@index')->name('index')->middleware('can:list-license');
            Route::get('/create', 'Admin\LicenseController@create')->name('create')->middleware('can:add-license');
            Route::post('/store', 'Admin\LicenseController@store')->name('store')->middleware('can:add-license');
            Route::get('/edit/{id}', 'Admin\LicenseController@edit')->name('edit')->middleware('can:edit-license');
            Route::post('/update/{id}', 'Admin\LicenseController@update')->name('update')->middleware('can:edit-license');
            Route::get('/destroy/{id}', 'Admin\LicenseController@destroy')->name('destroy')->middleware('can:delete-license');
        });
        
        Route::name('contracts.')->prefix('/contracts')->group(function () {
            Route::get('/', 'Admin\ContractController@index')->name('index')->middleware('can:list-contract');
            Route::get('/create', 'Admin\ContractController@create')->name('create')->middleware('can:add-contract');
            Route::post('/store', 'Admin\ContractController@store')->name('store')->middleware('can:add-contract');
            Route::get('/edit/{id}', 'Admin\ContractController@edit')->name('edit')->middleware('can:edit-contract');
            Route::post('/update/{id}', 'Admin\ContractController@update')->name('update')->middleware('can:edit-contract');
            Route::get('/destroy/{id}', 'Admin\ContractController@destroy')->name('destroy')->middleware('can:delete-contract');
            Route::get('/show/{id}', 'Admin\ContractController@show')->name('show')->middleware('can:show-contract');
        });

    });
});

Route::get('/', 'HomeController@index')->name('home.index');

resources/views/partials/admin/footer.blade.php
<footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
        Thang Long University
    </div>
    <!-- Default to the left -->
</footer>

resources/views/partials/admin/header.blade.php
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>
    
</nav>
<!-- /.navbar -->

resources/views/partials/admin/sidebar.blade.php
@section('css')
    <link rel="stylesheet" href="{{ asset('admin/profile/index.css') }}">
@endsection
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="/" class="brand-link">
        <span class="brand-text font-weight-light"><h5 style="text-align: center">Trang chủ</h5></span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                data-accordion="false">
                @can('list-user')
                    <li class="nav-item">
                        <a href="{{ route('admin.users.index') }}"
                            class="nav-link {{ Request::is('admin/users*') ? 'active' : '' }}">
                            <i class="fas fa-users"></i>
                            <p>
                                Quản lý người dùng
                            </p>
                        </a>
                    </li>
                @endcan
                @can('list-role')
                    <li class="nav-item">
                        <a href="{{ route('admin.roles.index') }}"
                            class="nav-link {{ Request::is('admin/roles*') ? 'active' : '' }}">
                            <i class="fas fa-user-tag"></i>
                            <p>
                                Quản lý vai trò
                            </p>
                        </a>
                    </li>
                @endcan
                @can('list-permission')
                    <li class="nav-item">
                        <a href="{{ route('admin.permissions.index') }}"
                            class="nav-link {{ Request::is('admin/permissions*') ? 'active' : '' }}">
                            <i class="fas fa-user-shield"></i>
                            <p>
                                Quản lý quyền truy cập
                            </p>
                        </a>
                    </li>
                @endcan
                @can('list-author')
                    <li class="nav-item">
                        <a href="{{ route('admin.authors.index') }}"
                            class="nav-link {{ Request::is('admin/authors*') ? 'active' : '' }} ">
                            <i class="fas fa-user-edit"></i>
                            <p>
                                Quản lý tác giả
                            </p>
                        </a>
                    </li>
                @endcan
                @can('list-product')
                    <li class="nav-item">
                        <a href="{{ route('admin.products.index') }}"
                            class="nav-link {{ Request::is('admin/products*') ? 'active' : '' }}">
                            <i class="fas fa-book"></i>
                            <p>
                                Quản lý tác phẩm
                            </p>
                        </a>
                    </li>
                @endcan
                @can('list-owner')
                    <li class="nav-item">
                        <a href="{{ route('admin.owners.index') }}"
                            class="nav-link {{ Request::is('admin/owners*') ? 'active' : '' }}">
                            <i class="fas fa-user-tie"></i>
                            <p>
                                Quản lý chủ sở hữu
                            </p>
                        </a>
                    </li>
                @endcan
                @can('list-license')
                    <li class="nav-item">
                        <a href="{{ route('admin.licenses.index') }}"
                            class="nav-link {{ Request::is('admin/licenses*') ? 'active' : '' }}">
                            <i class="fas fa-id-badge"></i>
                            <p>
                                Quản lý giấy phép
                            </p>
                        </a>
                    </li>
                @endcan
                @can('list-contract')
                    <li class="nav-item">
                        <a href="{{ route('admin.contracts.index') }}"
                            class="nav-link {{ Request::is('admin/contracts*') ? 'active' : '' }}">
                            <i class="fas fa-id-badge"></i>
                            <p>
                                Quản lý hợp đồng
                            </p>
                        </a>
                    </li>
                @endcan
                @can('list-category')
                    <li class="nav-item">
                        <a href="{{ route('admin.categories.index') }}"
                            class="nav-link {{ Request::is('admin/categories*') ? 'active' : '' }}">
                            <i class="fas fa-list-alt"></i>
                            <p>
                                Quản lý mục lục
                            </p>
                        </a>
                    </li>
                @endcan
                <li class="nav-item">
                    <a class="nav-link text-danger" href="{{ route('logout') }}"
                        onclick="event.preventDefault();
                                        document.getElementById('logout-form').submit();">
                        <i class="fas fa-sign-out-alt"></i>
                        <p>Đăng xuất</p>
                    </a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                        @csrf
                        <input type="hidden" name="url_redirect_name" value="admin.dashboard">
                    </form>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>