routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

Auth::routes();
Route::middleware('auth')->group(function () {
    //Role: admin
    Route::name('admin.')->prefix('admin')->group(function () {        
        Route::name('users.')->prefix('/users')->group(function () {
            Route::get('/', 'Admin\UserController@index')->name('index')->middleware('can:list-user');
            Route::get('/create', 'Admin\UserController@create')->name('create')->middleware('can:add-user');
            Route::post('/store', 'Admin\UserController@store')->name('store')->middleware('can:add-user');
            Route::get('/edit/{id}', 'Admin\UserController@edit')->name('edit')->middleware('can:edit-user');
            Route::post('/update/{id}', 'Admin\UserController@update')->name('update')->middleware('can:edit-user');
            Route::get('/destroy/{id}', 'Admin\UserController@destroy')->name('destroy')->middleware('can:delete-user');
        });

        Route::name('roles.')->prefix('/roles')->group(function () {
            Route::get('/', 'Admin\RoleController@index')->name('index')->middleware('can:list-role');
            Route::get('/create', 'Admin\RoleController@create')->name('create')->middleware('can:add-role');
            Route::post('/store', 'Admin\RoleController@store')->name('store')->middleware('can:add-role');
            Route::get('/edit/{id}', 'Admin\RoleController@edit')->name('edit')->middleware('can:edit-role');
            Route::post('/update/{id}', 'Admin\RoleController@update')->name('update')->middleware('can:edit-role');
            Route::get('/destroy/{id}', 'Admin\RoleController@destroy')->name('destroy')->middleware('can:delete-role');
        });

        Route::name('permissions.')->prefix('/permissions')->group(function () {
            Route::get('/', 'Admin\PermissionController@index')->name('index')->middleware('can:list-permission');
            Route::post('/store', 'Admin\PermissionController@store')->name('store')->middleware('can:add-permission');
            Route::get('/destroy/{id}', 'Admin\PermissionController@destroy')->name('destroy')->middleware('can:delete-permission');
        });

        // Role:editor or admin
        Route::name('authors.')->prefix('/authors')->group(function () {
            Route::get('/', 'Admin\AuthorController@index')->name('index')->middleware('can:list-author');
            Route::get('/create', 'Admin\AuthorController@create')->name('create')->middleware('can:add-author');
            Route::post('/store', 'Admin\AuthorController@store')->name('store')->middleware('can:add-author');
            Route::get('/edit/{id}', 'Admin\AuthorController@edit')->name('edit')->middleware('can:edit-author');
            Route::post('/update/{id}', 'Admin\AuthorController@update')->name('update')->middleware('can:edit-author');
            Route::get('/destroy/{id}', 'Admin\AuthorController@destroy')->name('destroy')->middleware('can:delete-author');
        });

        Route::name('products.')->prefix('/products')->group(function () {
            Route::get('/', 'Admin\ProductController@index')->name('index')->middleware('can:list-product');
            Route::get('/create', 'Admin\ProductController@create')->name('create')->middleware('can:add-product');
            Route::post('/store', 'Admin\ProductController@store')->name('store')->middleware('can:add-product');
            Route::get('/edit/{id}', 'Admin\ProductController@edit')->name('edit')->middleware('can:edit-product');
            Route::post('/update/{id}', 'Admin\ProductController@update')->name('update')->middleware('can:edit-product');
            Route::get('/show/{id}', 'Admin\ProductController@show')->name('show')->middleware('can:show-product');
            Route::get('/destroy/{id}', 'Admin\ProductController@destroy')->name('destroy')->middleware('can:delete-product');
        });

        Route::name('owners.')->prefix('/owners')->group(function () {
            Route::get('/', 'Admin\OwnerController@index')->name('index')->middleware('can:list-owner');
            Route::get('/create', 'Admin\OwnerController@create')->name('create')->middleware('can:add-owner');
            Route::post('/store', 'Admin\OwnerController@store')->name('store')->middleware('can:add-owner');
            Route::get('/edit/{id}', 'Admin\OwnerController@edit')->name('edit')->middleware('can:edit-owner');
            Route::post('/update/{id}', 'Admin\OwnerController@update')->name('update')->middleware('can:edit-owner');
            Route::get('/destroy/{id}', 'Admin\OwnerController@destroy')->name('destroy')->middleware('can:delete-owner');
        });

        Route::name('categories.')->prefix('/categories')->group(function () {
            Route::get('/', 'Admin\CategoryController@index')->name('index')->middleware('can:list-category');
            Route::post('/store', 'Admin\CategoryController@store')->name('store')->middleware('can:add-category');
            Route::get('/edit/{id}', 'Admin\CategoryController@edit')->name('edit')->middleware('can:edit-category');
            Route::post('/update/{id}', 'Admin\CategoryController@update')->name('update')->middleware('can:edit-category');
            Route::get('/destroy/{id}', 'Admin\CategoryController@destroy')->name('destroy')->middleware('can:delete-category');
        });

        Route::name('licenses.')->prefix('/licenses')->group(function () {
            Route::get('/', 'Admin\LicenseController@index')->name('index')->middleware('can:list-license');
            Route::get('/create', 'Admin\LicenseController@create')->name('create')->middleware('can:add-license');
            Route::post('/store', 'Admin\LicenseController@store')->name('store')->middleware('can:add-license');
            Route::get('/edit/{id}', 'Admin\LicenseController@edit')->name('edit')->middleware('can:edit-license');
            Route::post('/update/{id}', 'Admin\LicenseController@update')->name('update')->middleware('can:edit-license');
            Route::get('/destroy/{id}', 'Admin\LicenseController@destroy')->name('destroy')->middleware('can:delete-license');
        });
        
        Route::name('contracts.')->prefix('/contracts')->group(function () {
            Route::get('/', 'Admin\ContractController@index')->name('index')->middleware('can:list-contract');
            Route::get('/create', 'Admin\ContractController@create')->name('create')->middleware('can:add-contract');
            Route::post('/store', 'Admin\ContractController@store')->name('store')->middleware('can:add-contract');
            Route::get('/edit/{id}', 'Admin\ContractController@edit')->name('edit')->middleware('can:edit-contract');
            Route::post('/update/{id}', 'Admin\ContractController@update')->name('update')->middleware('can:edit-contract');
            Route::get('/destroy/{id}', 'Admin\ContractController@destroy')->name('destroy')->middleware('can:delete-contract');
            Route::get('/show/{id}', 'Admin\ContractController@show')->name('show')->middleware('can:show-contract');
        });

    });
});

Route::get('/', 'HomeController@index')->name('home.index');

resources/views/admin/licenses/create.blade.php
@extends('layouts.admin')
@section('title', 'Thêm mới giấy phép')
@section('css')
    <link rel="stylesheet" href="{{ asset('admin/user/create.css') }}">
@endsection
@section('content')
    <div class="content-wrapper">
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6">
                        <form action="{{ route('admin.licenses.store') }}" method="POST">
                            @csrf
                            <div class="form-group">
                                <label class="label-required" for="category_name">Tên giấy phép</label>
                                <input type="text" name="name" class="form-control" value="{{ old('name') }}">
                                @error('name')
                                    <span class="mt-1 text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label class="label-required">Chi phí</label>
                                <input type="number" min="0" name="fee" class="form-control" value="{{ old('fee') }}">
                                @error('fee')
                                <span class="mt-1 text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="category_name">Mô tả</label>
                                <textarea class="form-control" name="description" id="" cols="30" rows="10">{{ old('description') }}</textarea>
                                @error('description')
                                    <span class="mt-1 text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            <button type="submit" class="btn btn-primary mb-2">Thêm mới</button>
                        </form>
                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
@endsection

resources/views/admin/licenses/edit.blade.php
@extends('layouts.admin')
@section('title', 'Cập nhật giấy phép')
@section('css')
    <link rel="stylesheet" href="{{ asset('admin/user/create.css') }}">
@endsection
@section('content')
    <div class="content-wrapper">
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6">
                        <form action="{{ route('admin.licenses.update', ['id' => $license->id]) }}" method="POST">
                            @csrf
                            <div class="form-group">
                                <label  class="label-required" for="category_name">Tên giấy phép</label>
                                <input type="text" name="name" class="form-control" value="{{ old('name') ?? $license->name }}">
                                @error('name')
                                    <span class="mt-1 text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label  class="label-required">Chi phí</label>
                                <input type="number" min="0" name="fee" class="form-control" value="{{ old('fee') ?? $license->fee }}">
                                @error('fee')
                                <span class="mt-1 text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label  class="label-required" for="category_name">Mô tả</label>
                                <textarea class="form-control" name="description" id="" cols="30" rows="10">{{ old('description') ?? $license->description }}</textarea>
                                @error('description')
                                    <span class="mt-1 text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            <button type="submit" class="btn btn-primary mb-2">Thêm mới</button>
                        </form>
                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
@endsection

resources/views/admin/licenses/index.blade.php
@extends('layouts.admin')
@section('title', 'Quản lý giấy phép')
@section('content')
    <div class="content-wrapper">
        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="py-3">
                        <a class="btn btn-success btn-sm"
                            href="{{ route('admin.licenses.create') }}">Thêm mới</a>
                    </div>
                    <div class="col-md-12 card">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Tên</th>
                                    <th>Mô tả</th>
                                    <th>Chi phí</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($licenses as $license)
                                    <tr>
                                        <td>{{ $license->id }}</td>
                                        <td>{{ $license->name }}</td>
                                        <td>{{ $license->description }}</td>
                                        <td>{{ $license->fee }}</td>
                                        <td>
                                            <a href="{{ route('admin.licenses.edit', ['id' => $license->id]) }}"><button
                                                    class="btn btn-info btn-sm">Sửa</button></a>
                                            <button type="button"
                                                data-url="{{ route('admin.licenses.destroy', ['id' => $license->id]) }}"
                                                class="btn btn-danger btn-sm btn-delete">Xóa</button>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        {{ $licenses->withQueryString()->links() }}
                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
@endsection